### ISSUE TITLE
JMX Prometheus exporter configuration or yml file for the replicator

### ISSUE THREAD

**Issue by ptyagii** [confluentinc/jmx-monitoring-stacks#11]
Currently, there is no example for the JMX Prometheus exporter configuration or yml file for the replicator. 

We do have [connect JSON](https://github.com/confluentinc/jmx-monitoring-stacks/blob/5.5.0-post/jmxexporter-prometheus-grafana/assets/prometheus/grafana/provisioning/dashboards/connect.json) or [connect yml](https://github.com/confluentinc/jmx-monitoring-stacks/blob/5.5.0-post/jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/kafka-connect.yml), but no Prometheus JMX yaml template or example for replicator.

**Comment by Xytam** [comment]
Is this in reference to the standalone replicator executable?

**Comment by dsgroyanderson** [comment]
I have deployed a replicator configured connector to a connect cluster:

using the following configs:
```
{
	"name": "<hidden-replicator-name>",
	"config": {
		"connector.class": "io.confluent.connect.replicator.ReplicatorSourceConnector",
		"tasks.max": 4,
		"topic.regex": "<hidden prefix-topicName>|<hidden prefix-topicName>|<hidden prefix-topicName>|<hidden prefix-topicName>",
		"topic.whitelist": "",
		"topic.blacklist": "",
		"name": "<hidden-replicator-name>",
		"header.converter": "io.confluent.connect.replicator.util.ByteArrayConverter",
		"key.converter": "io.confluent.connect.replicator.util.ByteArrayConverter",
		"value.converter": "io.confluent.connect.replicator.util.ByteArrayConverter",
		"src.consumer.max.poll.records": "10000",
		"src.kafka.bootstrap.servers": "<HIDDEN URL>:<Hidden PORT>",
		"src.kafka.ssl.endpoint.identification.algorithm": "https",
		"src.kafka.security.protocol": "SASL_SSL",
		"src.kafka.sasl.mechanism": "PLAIN",
		"src.kafka.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"<HIDDEN>\" password=\"<HIDDEN>\";",
		"dest.kafka.bootstrap.servers": "<HIDDEN URL>:<Hidden PORT>",
		"dest.kafka.ssl.endpoint.identification.algorithm": "https",
		"dest.kafka.security.protocol": "SASL_SSL",
		"dest.kafka.sasl.mechanism": "PLAIN",
		"dest.kafka.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"<HIDDEN>\" password=\"<HIDDEN>\";",
		"provenance.header.enable": "true"
	}
}

```
I was unable to find any confluent docs that shows how to configure the JMX YAML file for replicator metrics. The only doc I found was a reference to an MBEAN for replicator.

Reference: https://docs.confluent.io/current/multi-dc-deployments/replicator/replicator-monitoring.html#important-crep-metrics

Therefore, I took the connect YAML file found: https://github.com/jeanlouisboudart/kafka-platform-prometheus/blob/master/jmx-exporter/kafka-connect.yml and added a custom rule using the MBean provide from the reference above. I do acknowledge I'm not a JMX expert and not sure if the configuration I was able to get to work based on my experience is working as expected.

While leaving the template the same I added this as the first rule:

```
rules:
- pattern: 'confluent.replicator.*'
    enable: true
    jmx:
            - object_name: confluent.replicator:type=confluent-replicator-task-metrics,confluent-replicator-task=([-.w]+),confluent-replicator-topic-name=([-.w]+),confluent-replicator-task-topic-partition=([-.w]+)
.
.
.
```

Finally, I wanted to point out two things:
1. When the original YAML config was deployed no confluent.replicator metrics are able to be seen in the JMX scrape.
2. It seems that if no replication is happening or a metrics is not available then no confluent.replicator metrics appear. Is that an accurate statement or why has this behavior been observed? For example, we can grep some confluent.replicator metrics on the AZ >> GCP replicator connect cluster where there is replication occurring and on the GCP >> AZ where no replication is happening and same config is deployed there is no metrics detected?

EXAMPLE on AZ >> GCP:
```
confluent_replicator_confluent_replicator_task_metrics_confluent_replicator_task_topic_partition_throughput{confluent_replicator_task="<hidden-replicator-name>-2",confluent_replicator_task_topic_partition="<Hidden-prefix-topic>-28",confluent_replicator_name="<hidden-replicator-name>",confluent_replicator_topic_name="<Hidden-prefix-topic>",} 0.0
.
.
.
confluent_replicator_confluent_replicator_task_metrics_confluent_replicator_task_topic_partition_message_lag{confluent_replicator_task="<hidden-replicator-name>-1",confluent_replicator_task_topic_partition="<Hidden-prefix-topic>-5",confluent_replicator_name="<hidden-replicator-name>",confluent_replicator_topic_name="<Hidden-prefix-topic>",} NaN
.
.
etc
```

What we are hoping for at this point is answers to the following:

1. How can we configure the YAML to pull replicator metrics?

For the following metrics (reference: https://docs.confluent.io/current/multi-dc-deployments/replicator/replicator-monitoring.html#important-crep-metrics):

> confluent-replicator-source-cluster
> The id of the source cluster from which Replicator is replicating.
> confluent-replicator-destination-cluster
> The id of the destination cluster to which Replicator is replicating.
> confluent-replicator-destination-topic-name
> The name of the destination topic to which Replicator is replicating.
> confluent-replicator-task-topic-partition-message-lag
> The number of messages that were produced to the origin cluster, but have not yet arrived to the destination cluster.
> confluent-replicator-task-topic-partition-throughput
> The number of messages replicated per second from the source to destination cluster.
> confluent-replicator-task-topic-partition-byte-throughput
> The number of bytes replicated per second from the source to destination cluster.
> confluent-replicator-task-topic-partition-latency
> The average time between message production to the source cluster and message production to the destination cluster.

2. Do you have supporting docs for this configuration?

3. Is it possible to reference the MBEAN that is provided in the aforementioned reference to determine a rule to use in the JMX YAML config file to pull the metrics and what would that look like?

**Comment by waliaabhishek** [comment]
Please try out the connect YAML files from the 6.0.0-post branch. We overhauled the JMX exporter configurations and made them clearer, simpler, and easier. I understand that they may not exactly match the bean names so, you might see some hiccups.
I will try to get a patch going for 550-post soon, as we are trying to reduce the verbosity of the replicator MBeans in another PR. As soon as that PR closes, I will try to add the replicator config to the 550-post branch to keep them aligned. 

The part which caters to the replicator metrics in that configuration is referenced [here](https://github.com/confluentinc/jmx-monitoring-stacks/blob/807e58202f10f99d683251cda27b09ba890e5757/jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/kafka_connect.yml#L87). Please feel free to respond here, if you feel that is not adequate.
