### ISSUE TITLE
Make "main" as the default branch

### ISSUE THREAD

**Issue by hifly81** [confluentinc/jmx-monitoring-stacks#113]
Currently default branch is set to 7.2.
could we use "main" instead?

**Comment by Schm1tz1** [comment]
Makes sense 👍 . We need someone with admin permissions for this repo to change that AFAIK.

**Comment by Schm1tz1** [comment]
@waliaabhishek Can you help us with this?

**Comment by Schm1tz1** [comment]
Resolved via Slack discussion.
