### ISSUE TITLE
Add metrics and dashboards for KRaft

### ISSUE THREAD

**Issue by ram-pi** [confluentinc/jmx-monitoring-stacks#131]
Add KRaft monitoring dashboards, JMX metrics to monitor [here](https://docs.confluent.io/platform/current/kafka-metadata/config-kraft.html#monitor-kraft).
We should also need to upgrade [prometheus.yml.j2](https://github.com/confluentinc/jmx-monitoring-stacks/blob/7.2-post/jmxexporter-prometheus-grafana/cp-ansible/templates/prometheus.yml.j2) to scrape metrics with prometheus.

**Comment by hifly81** [comment]
add
https://cwiki.apache.org/confluence/display/KAFKA/KIP-938%3A+Add+more+metrics+for+measuring+KRaft+performance

**Comment by hifly81** [comment]
I see a KRaft dashboard available for the dev-toolkit
@ram-pi is this usable for the top level list of dashboards?

**Comment by hifly81** [comment]
Those metrics are already available

https://docs.confluent.io/platform/current/kafka/monitoring.html#kraft-broker-metrics
https://docs.confluent.io/platform/current/kafka/monitoring.html#kraft-quorum-metrics
