### ISSUE TITLE
/jmxexporter-prometheus-grafana/docker-compose.local.yaml Is there any material for KRaft Mode like that file??

### ISSUE THREAD

**Issue by topyheun** [confluentinc/jmx-monitoring-stacks#141]
I am implementing a system monitored via prometheus, Grafana using docker-compose.yml in KRaft mode. It is very difficult due to the lack of data on KRaft mode (kafka, jmxexporter, prometheus, etc.). :(

**Comment by hifly81** [comment]
Hi @topyheun 
We are in a process of providing metrics and examples with KRaft mode. stay tuned
https://github.com/confluentinc/jmx-monitoring-stacks/issues/131

@ram-pi

**Comment by topyheun** [comment]
@hifly81 

    
This is my docker-compose file. What do you think?
I would be very grateful if you could give me very vicious and cold feedback.


version: '3'

services:
  broker1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@controller1:19092,5@controller2:29092,6@controller3:39092
      KAFKA_LOG_DIRS: /tmp/kraft-logs
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker1 -Dcom.sun.management.jmxremote.rmi.port=4000 -javaagent:/jmx_prometheus_javaagent-0.19.0.jar=7000:/jmxexporter.yml"
      JMX_PORT: 5000
    volumes:
      - broker1-data:/tmp/kraft-logs
      - ./jmx_prometheus_javaagent-0.19.0.jar:/jmx_prometheus_javaagent-0.19.0.jar
      - ./jmxexporter.yml:/jmxexporter.yml

    networks:
      - topy_monitoring_network

  controller1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "19092:19092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 4
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://controller1:19092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@controller1:19092,5@controller2:29092,6@controller3:39092
      KAFKA_LOG_DIRS: /tmp/kraft-logs
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=controller1 -Dcom.sun.management.jmxremote.rmi.port=4001 -javaagent:/jmx_prometheus_javaagent-0.19.0.jar=7001:/jmxexporter.yml"
      JMX_PORT: 5001
    volumes:
      - controller1-data:/tmp/kraft-logs
      - ./jmx_prometheus_javaagent-0.19.0.jar:/jmx_prometheus_javaagent-0.19.0.jar
      - ./jmxexporter.yml:/jmxexporter.yml
    networks:
      - topy_monitoring_network

  controller2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 5
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://controller2:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@controller1:19092,5@controller2:29092,6@controller3:39092
      KAFKA_LOG_DIRS: /tmp/kraft-logs
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=controller2 -Dcom.sun.management.jmxremote.rmi.port=4002 -javaagent:/jmx_prometheus_javaagent-0.19.0.jar=7002:/jmxexporter.yml"
      JMX_PORT: 5002
    volumes:
      - controller2-data:/tmp/kraft-logs
      - ./jmx_prometheus_javaagent-0.19.0.jar:/jmx_prometheus_javaagent-0.19.0.jar
      - ./jmxexporter.yml:/jmxexporter.yml
    networks:
      - topy_monitoring_network

  controller3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "39092:39092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 6
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://controller3:39092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@controller1:19092,5@controller2:29092,6@controller3:39092
      KAFKA_LOG_DIRS: /tmp/kraft-logs
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=controller3 -Dcom.sun.management.jmxremote.rmi.port=4003 -javaagent:/jmx_prometheus_javaagent-0.19.0.jar=7003:/jmxexporter.yml"
      JMX_PORT: 5003
    volumes:
      - controller3-data:/tmp/kraft-logs
      - ./jmx_prometheus_javaagent-0.19.0.jar:/jmx_prometheus_javaagent-0.19.0.jar
      - ./jmxexporter.yml:/jmxexporter.yml
    networks:
      - topy_monitoring_network

volumes:
  broker1-data:
  controller1-data:
  controller2-data:
  controller3-data:

networks:
  topy_monitoring_network:
    external: true

**Comment by hifly81** [comment]
> @hifly81
> 
> This is my docker-compose file. What do you think? I would be very grateful if you could give me very vicious and cold feedback.
> 
> ![image](https://user-images.githubusercontent.com/41532299/277307618-4a260ba0-68df-4b45-ae4b-4b8450201b20.png)

hey @topyheun it looks ok. but I can't say anything about metrics only looking at docker-compose. Could you please consider to open a PR for KRaft integration?

**Comment by hifly81** [comment]
Hi @topyheun we have added a first version for a kraft grafana dashbaord in dev-toolkit. I will close the issue.
Feel free to open it again for extended support
