### ISSUE TITLE
DEV-toolkit: spring-client provide image for arm64

### ISSUE THREAD

**Issue by hifly81** [confluentinc/jmx-monitoring-stacks#153]
spring-client The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by ram-pi** [comment]
It should be available now, let me know if it works

**Comment by hifly81** [comment]
> It should be available now, let me know if it works

in docker hub there is only a tag for
linux/arm/v7

we also need
linux/arm64/v8

**Comment by hifly81** [comment]
ok after manual deletion of image it works.
