### ISSUE TITLE
Add metrics and dashboard for Tiered Storage

### ISSUE THREAD

**Issue by hifly81** [confluentinc/jmx-monitoring-stacks#166]
https://docs.confluent.io/platform/current/kafka/tiered-storage.html#sizing-brokers-with-tiered-storage

**Comment by hifly81** [comment]
@pneff93

**Comment by hifly81** [comment]
hey @pneff93 I see that you are working on this 
https://github.com/pneff93/cp-tiered-storage

I'd be nice to provide also metrics and a dashbaord. wdyt?
I dont think the current exporter provides metrics for TS

**Comment by pneff93** [comment]
@hifly81,

alright, I will see what I can do

**Comment by hifly81** [comment]
fixed with https://github.com/confluentinc/jmx-monitoring-stacks/pull/189
