### ISSUE TITLE
Monitor Consumer Lag on brokers 

### ISSUE THREAD

**Issue by hifly81** [confluentinc/jmx-monitoring-stacks#169]
https://docs.confluent.io/platform/current/monitor/monitor-consumer-lag.html#monitor-consumer-lag

**Comment by hifly81** [comment]
see
https://forum.confluent.io/t/consumer-group-metrics-using-jmx/9794

**Comment by pneff93** [comment]
I try to block some time in February latest March to include it

**Comment by pneff93** [comment]
PR in cp-demo to enable consumer lag emitter: https://github.com/confluentinc/cp-demo/pull/453

**Comment by hifly81** [comment]
> PR in [cp-demo](https://github.com/confluentinc/cp-demo) to enable consumer lag emitter: [confluentinc/cp-demo#453](https://github.com/confluentinc/cp-demo/pull/453)

I think it also possible for us to add the property in docker-override file.
