### ISSUE TITLE
Monitoring  CFK using kube-prometheus-stack

### ISSUE THREAD

**Issue by eddycastillon** [confluentinc/jmx-monitoring-stacks#176]
Hello,

I am working on enable monitoring for Confluent Platform at prod environment, so I deployed two test clusters, the first using CP-Ansible and the second using CFK.
For the first deploy, I integrated it with Grafana and was able to see all the default Grafana dashboards provided by this repo. For the second deploy using CFK, I was able to:
- Install the operator kube-prometheus-stack
- Use the pm-confluent.yaml file to discover some Kafka metrics on Grafana

However, the metrics I discovered do not match the metrics expected by Grafana dashboards. All dashboards are not able to get data from Prometheus.

podMonitor

![image](https://github.com/confluentinc/jmx-monitoring-stacks/assets/15278235/27ffe475-7410-4ee5-bdb9-2a000ecb0ad6)

Let me give you an example:

One metric expected by grafana dashboard is "_kafka_log_log_size_". However I am not receiving this metric. Exploring the metrics discovered, I see metrics related to "_kafka_log_log_value_".

![image](https://github.com/confluentinc/jmx-monitoring-stacks/assets/15278235/7de9fd48-c6dc-46da-b408-563b0fc277da)

I am not sure what is pending to enable the metrics expected by the default dashboards like CP-ansible.

Thank in advanced.

**Comment by hifly81** [comment]
@eddycastillon as reported in doc https://github.com/confluentinc/jmx-monitoring-stacks/tree/main/jmxexporter-prometheus-grafana/cfk,  Use the cfk/update-dashboards.sh

**Comment by hifly81** [comment]
@eddycastillon have you had a try using the script  _cfk/update-dashboards.sh_ ?

**Comment by eddycastillon** [comment]
Hi @hifly81:
After a double check reviewing the documentation, i forgot enable the Prometheus rules. After enabling the Prometheus rules, I can discover the metrics expected by the update dashboards (cfk/update-dashboards.sh).

Thank you for your support.

Regards
Eddy Castillon
