### ISSUE TITLE
CFK Dashboard throws "Failed to upgrade legacy queries Datasource PBFA97CFB590B2093 was not found" error

### ISSUE THREAD

**Issue by wombat** [confluentinc/jmx-monitoring-stacks#200]
I used the README under (https://github.com/confluentinc/jmx-monitoring-stacks/tree/main/jmxexporter-prometheus-grafana/cfk), ran the `update-dashboards.sh` and imported the confluent-platform dashboard into our Grafana instance within OpenShift.

Unfortunately I only get the error: `Failed to upgrade legacy queries Datasource PBFA97CFB590B2093 was not found`.

I also see no input variable for the prometheus datasource in the dashboard.

**Comment by wombat** [comment]
I have tried the other dashboards too - none of them work!
I verified that the PodMonitor is active and Prometheus successfully scraped the prometheus endpoints of kafka, zookeeper, ksqldb, controlcenter and schemaregistry.
I manually port-forwarded the individual ports to see if metrics a exported and I can see a log of metrics coming from the endpoints.

**Comment by wombat** [comment]
I also now tried to fix the datasource myself and the confluent-platform dashboard has avariable `namespace`, which queries the label values of `kafka_server_kafkaserver_brokerstate`: From which endpoints should this metric come from? I have looked through all prometheus endpoints and I couldn´t find it

**Comment by hifly81** [comment]
Hi @wombat 
have you tried?
https://community.grafana.com/t/should-provisioned-dashboards-have-datasource-uids/65463/3

["](https://community.grafana.com/t/should-provisioned-dashboards-have-datasource-uids/65463/2)

**Comment by wombat** [comment]
The dashboards should in general be exported from Grafana with the `Export for sharing externally` - this way Grafana adds an input variable upon import.

**Comment by hifly81** [comment]
> The dashboards should in general be exported from Grafana with the `Export for sharing externally` option enabled - this way Grafana adds an input variable to the exported dashboard.

thanks for sharing this; we will regenerate them with option enabled and fix the issue

**Comment by wombat** [comment]
Thanks!

**Comment by wombat** [comment]
Does this only fix the datasource?

What about the metrics that I cannot find?

**Comment by hifly81** [comment]
yep @wombat 
could you pls open a new issue only limited to metrics?

thanks

**Comment by hifly81** [comment]
@wombat added a new demo for cfk thanks to @ram-pi
