### ISSUE TITLE
Add JMX metrics to capture the consumer lag from Kafka clusters

### ISSUE THREAD

**Issue by vrindavda** [confluentinc/jmx-monitoring-stacks#211]
Add [consumer](https://docs.confluent.io/platform/current/kafka/monitoring.html#consumer-lag-offsets) related  metrics in these examples: https://github.com/confluentinc/jmx-monitoring-stacks/blob/7.3-post/shared-assets/jmx-exporter/kafka_broker.yml

**Comment by hifly81** [comment]
Hi @vrindavda this has been recently added by @pneff93 with PR
https://github.com/confluentinc/jmx-monitoring-stacks/pull/203
