### ISSUE TITLE
dev-toolkit- image for spring demo client should be available for arm and amd arch

### ISSUE THREAD

**Issue by hifly81** [confluentinc/jmx-monitoring-stacks#229]

**Comment by hifly81** [comment]
it seems that the behavior is sporadic and leads to a jvm fault with segmentation fault

_java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Homebrew (build 17.0.11+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.11+0, mixed mode, sharing)_

**Comment by ram-pi** [comment]
It should work now with a temurin-based docker image.
