### ISSUE TITLE
Missing metrics in prometheus exporter

### ISSUE THREAD

**Issue by lavalex** [confluentinc/jmx-monitoring-stacks#243]
Hello,

When I tried to use kafka_broker.yml I noticed for example that all kafka_controller* metrics are missing. If I try exporter with no rules, I do see that metric.

I think the issue is somewhere here:

https://github.com/confluentinc/jmx-monitoring-stacks/blob/509334cf3988d23f3d66387fef811774d37dc41f/shared-assets/jmx-exporter/kafka_broker.yml#L145  ?

Thanks.

**Comment by hifly81** [comment]
Hi @lavalex 

I tried using dev-toolkit

_dev-toolkit/start.sh_

then I have scraped all prometheus metrics from broker 1:

_curl -v http://kafka1:1234/metrics >> /tmp/metrics.txt_

and _kafka_controller_ metrics are visible (see img)

![Screenshot 2024-07-18 alle 11 00 44](https://github.com/user-attachments/assets/e57ceda4-8df3-4c6a-909f-663692826fa0)

could you pls try it?
