### ISSUE TITLE
Cluster Linking dashboard - instance variable

### ISSUE THREAD

**Issue by ram-pi** [confluentinc/jmx-monitoring-stacks#247]
As in the image below, the `instance` variable come from label_values where `env` is used. 
Since this variable isn't used in k8s deployment, should we find something else?

![image](https://github.com/user-attachments/assets/230faccc-2f36-47f6-9f3f-22d2b8b28fb5)

**Comment by hifly81** [comment]
script _update-dashboards.sh_ in cfk folder need to be executed before using the dashboards for Kubernetes
