### ISSUE TITLE
How to expose kafka_consumer_* and kafka_producer_* metrics?

### ISSUE THREAD

**Issue by kholis** [confluentinc/jmx-monitoring-stacks#290]
Hi,

I've add this config to kafka-broker, but no `kafka_consumer_*` and `kafka_producer_*` metrics show up. 

`-javaagent:/tmp/jmx_prometheus_javaagent-1.1.0.jar=1234:/tmp/kafka_config.yml`

Both files taken from [shared-assets](https://github.com/confluentinc/jmx-monitoring-stacks/tree/main/shared-assets/jmx-exporter)

How to expose those metrics?

Regards,

**Comment by hifly81** [comment]
Hi @kholis 
_kafka_consumer_ and _kafka_producer_ metrics are meant toi be used with java clients applications.

You need to instruct the jvm of your client applications to use then _kafka_client.yml_

HTH

**Comment by kholis** [comment]
Hi @hifly81 

In case we use non-java producer/consumer, let's say python. How to expose this metrics?

Appreciate your answer.

**Comment by hifly81** [comment]
Hi @kholis 
for non java apps, you need to use a librdkafka client wrapper, available for multiple languages (including python).
We have an example for a .NET librdkafka based app but you can adapt for python as well

https://github.com/confluentinc/jmx-monitoring-stacks/tree/main/jmxexporter-prometheus-grafana/librdkafka
