### ISSUE TITLE
Add alerts to Grafana dashboards

### ISSUE THREAD

**Issue by jeqo** [confluentinc/jmx-monitoring-stacks#30]
So far only Zookeeper has alerts defined.

Dashboards should include alerts based on recommendations from https://docs.confluent.io/platform/current/kafka/monitoring.html.

**Comment by gitfrog0** [comment]
I've created a set of alerts for Prometheus for the most important metrics.

**Comment by jeqo** [comment]
@gitfrog0 interesting. Would be good to discuss and propose different alternatives for alerting. e.g. Zookeeper alerts are at Grafana at the moment.

cc @waliaabhishek wdyt? would this be something we could consider adding into this repo?

**Comment by hifly81** [comment]
added alerts for core metrics with commit
https://github.com/confluentinc/jmx-monitoring-stacks/commit/b56945f23b6be9a937dc3cbd16ab9201cddb5551
