### ISSUE TITLE
Questions regarding panels in Grafana

### ISSUE THREAD

**Issue by arnoldyahad** [confluentinc/jmx-monitoring-stacks#35]
Hey guys,
first of all - thanks for the demo, it works great!

i'm interested in implementing some of the dashboard and the producer dashboard has this panel:

![image](https://user-images.githubusercontent.com/18227724/118112855-3c49f400-b3ee-11eb-8ab4-03cc80a5ecb0.png)
i'm only selecting 1 client id, can you please explain why there are 30+ panels(i would expect only 1 panel that shows the compression rate of that client) 

same for retry rate:
![image](https://user-images.githubusercontent.com/18227724/118113267-bed2b380-b3ee-11eb-86e1-3dfeaec98ed5.png)
selecting only 1 client_id, and i get tons of panel, while logically i only expect 1 panel to appear(or at least 1 panel per 1 client if "All" is elected)

(some labels were changed to fit our solution as you might notice) 

Thanks a lot for reading!

**Comment by jeqo** [comment]
Hi there, client dashboards have been updated #56. 
Check them out https://github.com/confluentinc/jmx-monitoring-stacks/tree/6.1.0-post/jmxexporter-prometheus-grafana#kafka-clients.
Will close this one, but feel free to reopen if you think this hasn't been solved.
