### ISSUE TITLE
Suggest adding new metadata service metrics

### ISSUE THREAD

**Issue by cotedm** [confluentinc/jmx-monitoring-stacks#40]
An important one would be the MDS writer. Similar to a Controller, we should monitor to ensure there is a single writer:

confluent.metadata:type=KafkaAuthStore,name=active-writer-count

Keeping a running count of total role binding's to compare against the soft limit is also useful:

confluent-auth-store-metrics:name=rbac-role-bindings-count

**Comment by hifly81** [comment]
added with commit
https://github.com/confluentinc/jmx-monitoring-stacks/commit/f01555c86c388a6a43b7448813f31e9c10a7c7ad
