### ISSUE TITLE
Consumer/Producer dashboard with 'No Data (red)' in some widgets

### ISSUE THREAD

**Issue by mcascallares** [confluentinc/jmx-monitoring-stacks#42]
Hi,

I just started jmx-monitoring-stacks with cp-demo, both using 6.1.0-post, and for producer and consumer dashboards I don't have data for some of the widgets. Is this the expected behavoir?

I also tried creating a topic and starting to produce data and nothing:

docker exec kafka1 bash -c 'KAFKA_OPTS="" kafka-topics --create --topic my-topic --partitions 3 --replication-factor 2 --bootstrap-server kafka1:12091'

docker exec kafka1 bash -c 'KAFKA_OPTS="" kafka-producer-perf-test --throughput 500 --num-records 100000000 --topic my-topic --record-size 1000 --producer-props bootstrap.servers=kafka1:12091'

Thanks!

<img width="1432" alt="Screenshot 2021-08-23 at 16 02 26" src="https://user-images.githubusercontent.com/481932/130460896-a40b072d-b70f-4a2b-939f-d175b403a9a4.png">
<img width="1440" alt="Screenshot 2021-08-23 at 16 02 37" src="https://user-images.githubusercontent.com/481932/130460908-e94b79d1-83dc-4035-b413-ccdcf0bd7937.png">

**Comment by jeqo** [comment]
@mcascallares thanks for reporting this, and sorry for the delay.
I started to work on this to update the client dashboards to include all client_ids.
If you could take a look at https://github.com/confluentinc/jmx-monitoring-stacks/pull/56 and give some feedback would be awesome.

@nuriel77 your scenario seems a bit broader than the issue reporter.  If the issue persists on your side, would you mind opening a new ticket explaining your setup? Thanks!
