### ISSUE TITLE
Make tutorials for this repo available through gitpod

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/jmx-monitoring-stacks#53]
Recently, CP Demo added the ability to [run in gitpod](https://docs.confluent.io/platform/current/tutorials/cp-demo/docs/on-prem.html#gitpod) so that users can get hands on experience with 1 click and 0 setup. This repo might benefit as well.

**Comment by hifly81** [comment]
added with commit
https://github.com/confluentinc/jmx-monitoring-stacks/commit/58e547bc2b53bff1e98ba113706030c8dad7222c
