### ISSUE TITLE
Discrepency between blog post and confluent docs.

### ISSUE THREAD

**Issue by JeroenSchmidt** [confluentinc/jmx-monitoring-stacks#55]
Thank you for putting this repository together. It  has helped me quite a lot in understanding the relationship between JMX, Kafka components, grafana and prometheus. 

I have a question related to the [blog post related to this repo](https://www.confluent.io/blog/monitor-kafka-clusters-with-prometheus-grafana-and-confluent/)  and some confusion that the official documentation has caused me.

The confluent [documentation on connector monitoring](https://docs.confluent.io/home/connect/monitoring.html#using-jmx-to-monitor-kconnect)  mentions "Connect can be configured to report stats using additional pluggable stats reporters using the `metric.reporters` configuration option". My understanding of that sentence is that it needs to be set in-order to serve JMX metrics however this confuses me because I can't see any usage of  it for the connector agents within`jmx-monitoring-stacks/jmxexporter-prometheus-grafana` and the `cp-demo` repo. 

Q1) Is it actually the case that in order to expose JMX metrics from the connector all that needs to happen is for `EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=1234:/usr/share/jmx-exporter/kafka_connect.yml` to be set and for the jmx exporter configs to be present on the machine?

Q2) As a followup question; why is it that only the `kafka1` and `kafka2` containers have the `KAFKA_METRIC_REPORTERS` properties set and yet all the other services are still able to expose metrics to prometheus?

**Comment by jeqo** [comment]
Hi there! Thanks for the kind words :) 

`metric.reporters` is meant to include _additional_ reporters:

https://github.com/apache/kafka/blob/cc1aa3b83d22dfe45fab945c3958325d87858a8f/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/ConnectMetrics.java#L79-L86

Q1: JMX metrics are always exposed. Adding JMX Exporter java agent leverages this to expose metrics in Prometheus format at port 1234 using kafka_connect.yml configuration file.

Q2:

https://github.com/confluentinc/cp-demo/blob/430e522dd43015fd28284554b970e94e45721678/docker-compose.yml#L159

Is used to include an additional reporter to push metrics for Control Center to monitor.

Hope this clarifies a bit.

**Comment by jeqo** [comment]
@JeroenSchmidt will b e closing this one for now. 
Feel free to reopen if you feel it's not answered.
Cheers,

**Comment by JeroenSchmidt** [comment]
Thank you @jeqo for your help! :)
