### ISSUE TITLE
Missing metrics on kafka connect

### ISSUE THREAD

**Issue by alex88** [confluentinc/jmx-monitoring-stacks#67]
I've tried to import the kafka connect grafana+prometheus dashboard and use it with the kafka connect installed by the [helm](https://github.com/confluentinc/cp-helm-charts) chart however all data is missing.

I can see for example the dashboard uses `kafka_connect_connect_worker_metrics_connector_total_task_count` for the total tasks but the jmx exporter uses `cp_kafka_connect_connect_worker_metrics_task_count`, am I missing something?

**Comment by alex88** [comment]
Update: after copying the jmx exporter config I was able to get more metriics, however I'm still missing the jvm ones (heap, memory)

**Comment by hifly81** [comment]
Hi @alex88 still having issues?

**Comment by hifly81** [comment]
closed due to inactivity
