### ISSUE TITLE
Metrics don't appear in dashboards: $broker_id and $env are blank

### ISSUE THREAD

**Issue by kebarcla** [confluentinc/jmx-monitoring-stacks#7]
Hello!
Would like to know if you have some pointers to debug this - I have cp-demo running & the Grafana & Prometheus dashboards come up. And in Prometheus I can see all the metrics, and if I pull up for example kafka_server_kafkaserver_brokerstate, I can see env="dev",instance="kafka1", etc.
But $broker_id and $env in Grafana Variables are blank, so none of the queries are working.

If I hack a query to remove the vars I can see the metrics plotted for kafka1 and kafka2:
rate(process_cpu_seconds_total{job="kafka",env="dev"}[3m])

Is the label_values function failing? Not sure how to debug this.
Thanks
Ken

7/6

I've seen weirdness in Grafana about getting metrics before so I did something I've tried before:
- Went in to the Variables section, selected a variable, saved it again without making changes
- Then, briefly, almost all of the Kafka Overview metrics appeared. It's quite a nice dashboard: very detailed.

And in the case of my own production dashboards that will usually last as long as I have the session running.
In this case it stopped working as soon as I navigated away, and I could never get it working again, despite messing with variables some more.

There's something very flaky and touchy about Grafana that I have never been able to figure out.

**Comment by ybyzek** [comment]
cc @jeanlouisboudart for input

**Comment by jeanlouisboudart** [comment]
Hello @kebarcla, thanks for reporting this.

Possible values for the variables are refreshed when you load the dashboard. 
If at that time metrics were not available the dropdown will not contain anything. Try hitting a refresh in your browser to see if it solves the problems.

Alternatively, you can change the refresh strategy in the variable configuration page and choose for example "On Time Range Change"
![image](https://user-images.githubusercontent.com/374409/87323020-7c221f80-c52e-11ea-8abd-5eda2a2588d0.png)

Let me know if that solves the problems.

Cheers,
Jean-Louis

**Comment by kebarcla** [comment]
Hi Jean-Louis,
Per your suggestion I again verified metrics are coming in via Prometheus, then changed the Variables' Refresh to 'On Time Range Change' for all 3 variables in the Kafka Overview dashboard. This at first still showed 'No Data' for everything, but at one point I tried 'Last 1 Hour' as a time interval, and except for 'Zookeeper' and 'ISR Shrinks', the rest of the metrics filled in!
This is real progress. Unfortunately I could not get any other dashboards to work: I did the Variable setting change for Kafka Lag Exported & verified for example that kafka_consumergroup_group_max_lag_seconds was viable, but no metrics for that or any other dashboard showed up, at any time interval.
I thought I had it! Really baffling.
Thanks for your help: let me know if you've other suggestions!
- Ken


    On Monday, July 13, 2020, 08:35:53 AM PDT, Jean-Louis Boudart <notifications@github.com> wrote:  
 
 


Hello @kebarcla, thanks for reporting this.

Possible values for the variables are refreshed when you load the dashboard.
If at that time metrics were not available the dropdown will not contain anything. Try hitting a refresh in your browser to see if it solves the problems.

Alternatively, you can change the refresh strategy in the variable configuration page and choose for example "On Time Range Change"


Let me know if that solves the problems.

Cheers,
Jean-Louis

**Comment by Xytam** [comment]
No further updates on this issue, latest branch seems to have the issues resolved provided there is a small wait period which is standard for startup (generally 5 minutes or less)
