### ISSUE TITLE
missing metric for zookeeeper clients online

### ISSUE THREAD

**Issue by michelmondor-sc** [confluentinc/jmx-monitoring-stacks#71]
can you please look into that, this metric does not exist

<img width="800" alt="image" src="https://user-images.githubusercontent.com/99200994/156430642-64f06d79-31ee-4048-8e80-e55fae346783.png">

count(zookeeper_status_quorumsize{job="zookeeper",env="$env"}) 

returns N/A

and does not exist in the metric shown

`# HELP jvm_classes_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_loaded gauge
jvm_classes_loaded 3475.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 3475.0
# HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
# TYPE jvm_classes_unloaded_total counter
jvm_classes_unloaded_total 0.0
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.16.1",name="jmx_prometheus_javaagent",} 1.0
# HELP jvm_buffer_pool_used_bytes Used bytes of a given JVM buffer pool.
# TYPE jvm_buffer_pool_used_bytes gauge
jvm_buffer_pool_used_bytes{pool="mapped",} 0.0
jvm_buffer_pool_used_bytes{pool="direct",} 313156.0
# HELP jvm_buffer_pool_capacity_bytes Bytes capacity of a given JVM buffer pool.
# TYPE jvm_buffer_pool_capacity_bytes gauge
jvm_buffer_pool_capacity_bytes{pool="mapped",} 0.0
jvm_buffer_pool_capacity_bytes{pool="direct",} 313156.0
# HELP jvm_buffer_pool_used_buffers Used buffers of a given JVM buffer pool.
# TYPE jvm_buffer_pool_used_buffers gauge
jvm_buffer_pool_used_buffers{pool="mapped",} 0.0
jvm_buffer_pool_used_buffers{pool="direct",} 15.0
# HELP jvm_memory_objects_pending_finalization The number of objects waiting in the finalizer queue.
# TYPE jvm_memory_objects_pending_finalization gauge
jvm_memory_objects_pending_finalization 0.0
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 2.17100032E8
jvm_memory_bytes_used{area="nonheap",} 4.1909328E7
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 5.36870912E8
jvm_memory_bytes_committed{area="nonheap",} 4.4630016E7
# HELP jvm_memory_bytes_max Max (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_max gauge
jvm_memory_bytes_max{area="heap",} 5.36870912E8
jvm_memory_bytes_max{area="nonheap",} -1.0
# HELP jvm_memory_bytes_init Initial bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_init gauge
jvm_memory_bytes_init{area="heap",} 5.36870912E8
jvm_memory_bytes_init{area="nonheap",} 7667712.0
# HELP jvm_memory_pool_bytes_used Used bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_used gauge
jvm_memory_pool_bytes_used{pool="CodeHeap 'non-nmethods'",} 1261440.0
jvm_memory_pool_bytes_used{pool="Metaspace",} 2.4576672E7
jvm_memory_pool_bytes_used{pool="CodeHeap 'profiled nmethods'",} 9572096.0
jvm_memory_pool_bytes_used{pool="Compressed Class Space",} 2402736.0
jvm_memory_pool_bytes_used{pool="G1 Eden Space",} 1.96083712E8
jvm_memory_pool_bytes_used{pool="G1 Old Gen",} 1.9967744E7
jvm_memory_pool_bytes_used{pool="G1 Survivor Space",} 1048576.0
jvm_memory_pool_bytes_used{pool="CodeHeap 'non-profiled nmethods'",} 4096384.0
# HELP jvm_memory_pool_bytes_committed Committed bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_committed gauge
jvm_memory_pool_bytes_committed{pool="CodeHeap 'non-nmethods'",} 2555904.0
jvm_memory_pool_bytes_committed{pool="Metaspace",} 2.555904E7
jvm_memory_pool_bytes_committed{pool="CodeHeap 'profiled nmethods'",} 9633792.0
jvm_memory_pool_bytes_committed{pool="Compressed Class Space",} 2752512.0
jvm_memory_pool_bytes_committed{pool="G1 Eden Space",} 3.37641472E8
jvm_memory_pool_bytes_committed{pool="G1 Old Gen",} 1.98180864E8
jvm_memory_pool_bytes_committed{pool="G1 Survivor Space",} 1048576.0
jvm_memory_pool_bytes_committed{pool="CodeHeap 'non-profiled nmethods'",} 4128768.0
# HELP jvm_memory_pool_bytes_max Max bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_max gauge
jvm_memory_pool_bytes_max{pool="CodeHeap 'non-nmethods'",} 5828608.0
jvm_memory_pool_bytes_max{pool="Metaspace",} -1.0
jvm_memory_pool_bytes_max{pool="CodeHeap 'profiled nmethods'",} 1.22912768E8
jvm_memory_pool_bytes_max{pool="Compressed Class Space",} 1.073741824E9
jvm_memory_pool_bytes_max{pool="G1 Eden Space",} -1.0
jvm_memory_pool_bytes_max{pool="G1 Old Gen",} 5.36870912E8
jvm_memory_pool_bytes_max{pool="G1 Survivor Space",} -1.0
jvm_memory_pool_bytes_max{pool="CodeHeap 'non-profiled nmethods'",} 1.22916864E8
# HELP jvm_memory_pool_bytes_init Initial bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_init gauge
jvm_memory_pool_bytes_init{pool="CodeHeap 'non-nmethods'",} 2555904.0
jvm_memory_pool_bytes_init{pool="Metaspace",} 0.0
jvm_memory_pool_bytes_init{pool="CodeHeap 'profiled nmethods'",} 2555904.0
jvm_memory_pool_bytes_init{pool="Compressed Class Space",} 0.0
jvm_memory_pool_bytes_init{pool="G1 Eden Space",} 2.8311552E7
jvm_memory_pool_bytes_init{pool="G1 Old Gen",} 5.0855936E8
jvm_memory_pool_bytes_init{pool="G1 Survivor Space",} 0.0
jvm_memory_pool_bytes_init{pool="CodeHeap 'non-profiled nmethods'",} 2555904.0
# HELP jvm_memory_pool_collection_used_bytes Used bytes after last collection of a given JVM memory pool.
# TYPE jvm_memory_pool_collection_used_bytes gauge
jvm_memory_pool_collection_used_bytes{pool="G1 Eden Space",} 0.0
jvm_memory_pool_collection_used_bytes{pool="G1 Old Gen",} 0.0
jvm_memory_pool_collection_used_bytes{pool="G1 Survivor Space",} 1048576.0
# HELP jvm_memory_pool_collection_committed_bytes Committed after last collection bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_collection_committed_bytes gauge
jvm_memory_pool_collection_committed_bytes{pool="G1 Eden Space",} 3.37641472E8
jvm_memory_pool_collection_committed_bytes{pool="G1 Old Gen",} 0.0
jvm_memory_pool_collection_committed_bytes{pool="G1 Survivor Space",} 1048576.0
# HELP jvm_memory_pool_collection_max_bytes Max bytes after last collection of a given JVM memory pool.
# TYPE jvm_memory_pool_collection_max_bytes gauge
jvm_memory_pool_collection_max_bytes{pool="G1 Eden Space",} -1.0
jvm_memory_pool_collection_max_bytes{pool="G1 Old Gen",} 5.36870912E8
jvm_memory_pool_collection_max_bytes{pool="G1 Survivor Space",} -1.0
# HELP jvm_memory_pool_collection_init_bytes Initial after last collection bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_collection_init_bytes gauge
jvm_memory_pool_collection_init_bytes{pool="G1 Eden Space",} 2.8311552E7
jvm_memory_pool_collection_init_bytes{pool="G1 Old Gen",} 5.0855936E8
jvm_memory_pool_collection_init_bytes{pool="G1 Survivor Space",} 0.0
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 50.0
jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 0.13
jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
jvm_gc_collection_seconds_sum{gc="G1 Old Generation",} 0.0
# HELP jvm_memory_pool_allocated_bytes_total Total bytes allocated in a given JVM memory pool. Only updated after GC, not continuously.
# TYPE jvm_memory_pool_allocated_bytes_total counter
jvm_memory_pool_allocated_bytes_total{pool="CodeHeap 'profiled nmethods'",} 9571200.0
jvm_memory_pool_allocated_bytes_total{pool="G1 Old Gen",} 2.045016E7
jvm_memory_pool_allocated_bytes_total{pool="G1 Eden Space",} 9.910091776E9
jvm_memory_pool_allocated_bytes_total{pool="CodeHeap 'non-profiled nmethods'",} 4062464.0
jvm_memory_pool_allocated_bytes_total{pool="G1 Survivor Space",} 4194304.0
jvm_memory_pool_allocated_bytes_total{pool="Compressed Class Space",} 2402736.0
jvm_memory_pool_allocated_bytes_total{pool="Metaspace",} 2.4576304E7
jvm_memory_pool_allocated_bytes_total{pool="CodeHeap 'non-nmethods'",} 1267200.0
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 35.0
# HELP jvm_threads_daemon Daemon thread count of a JVM
# TYPE jvm_threads_daemon gauge
jvm_threads_daemon 20.0
# HELP jvm_threads_peak Peak thread count of a JVM
# TYPE jvm_threads_peak gauge
jvm_threads_peak 35.0
# HELP jvm_threads_started_total Started thread count of a JVM
# TYPE jvm_threads_started_total counter
jvm_threads_started_total 36.0
# HELP jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE jvm_threads_deadlocked gauge
jvm_threads_deadlocked 0.0
# HELP jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE jvm_threads_deadlocked_monitor gauge
jvm_threads_deadlocked_monitor 0.0
# HELP jvm_threads_state Current count of threads by state
# TYPE jvm_threads_state gauge
jvm_threads_state{state="TERMINATED",} 0.0
jvm_threads_state{state="WAITING",} 13.0
jvm_threads_state{state="NEW",} 0.0
jvm_threads_state{state="TIMED_WAITING",} 13.0
jvm_threads_state{state="BLOCKED",} 0.0
jvm_threads_state{state="RUNNABLE",} 9.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP zookeeper_connections_sessiontimeout SessionTimeout (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>SessionTimeout)
# TYPE zookeeper_connections_sessiontimeout untyped
zookeeper_connections_sessiontimeout{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 18000.0
# HELP zookeeper_commitprocmaxreadbatchsize CommitProcMaxReadBatchSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>CommitProcMaxReadBatchSize)
# TYPE zookeeper_commitprocmaxreadbatchsize gauge
zookeeper_commitprocmaxreadbatchsize 0.0
# HELP zookeeper_connectiontokenfillcount ConnectionTokenFillCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionTokenFillCount)
# TYPE zookeeper_connectiontokenfillcount gauge
zookeeper_connectiontokenfillcount 1.0
# HELP zookeeper_connections_maxlatency MaxLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>MaxLatency)
# TYPE zookeeper_connections_maxlatency untyped
zookeeper_connections_maxlatency{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 148.0
# HELP zookeeper_connections_packetsreceived PacketsReceived (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>PacketsReceived)
# TYPE zookeeper_connections_packetsreceived untyped
zookeeper_connections_packetsreceived{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 2192.0
# HELP zookeeper_authfailedcount AuthFailedCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>AuthFailedCount)
# TYPE zookeeper_authfailedcount gauge
zookeeper_authfailedcount 0.0
# HELP zookeeper_jutemaxbuffersize JuteMaxBufferSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>JuteMaxBufferSize)
# TYPE zookeeper_jutemaxbuffersize gauge
zookeeper_jutemaxbuffersize 1048575.0
# HELP zookeeper_connectiondropdecrease ConnectionDropDecrease (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionDropDecrease)
# TYPE zookeeper_connectiondropdecrease gauge
zookeeper_connectiondropdecrease 0.002
# HELP zookeeper_packetssent PacketsSent (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>PacketsSent)
# TYPE zookeeper_packetssent gauge
zookeeper_packetssent 17358.0
# HELP zookeeper_nonmtlsremoteconncount NonMTLSRemoteConnCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>NonMTLSRemoteConnCount)
# TYPE zookeeper_nonmtlsremoteconncount gauge
zookeeper_nonmtlsremoteconncount 0.0
# HELP zookeeper_connections_minlatency MinLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>MinLatency)
# TYPE zookeeper_connections_minlatency untyped
zookeeper_connections_minlatency{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 0.0
# HELP zookeeper_ticktime TickTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>TickTime)
# TYPE zookeeper_ticktime gauge
zookeeper_ticktime 2000.0
# HELP zookeeper_minclientresponsesize MinClientResponseSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MinClientResponseSize)
# TYPE zookeeper_minclientresponsesize gauge
zookeeper_minclientresponsesize 16.0
# HELP zookeeper_maxrequestlatency MaxRequestLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxRequestLatency)
# TYPE zookeeper_maxrequestlatency gauge
zookeeper_maxrequestlatency 288.0
# HELP zookeeper_maxsessiontimeout MaxSessionTimeout (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxSessionTimeout)
# TYPE zookeeper_maxsessiontimeout gauge
zookeeper_maxsessiontimeout 40000.0
# HELP zookeeper_requestthrottlestalltime RequestThrottleStallTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>RequestThrottleStallTime)
# TYPE zookeeper_requestthrottlestalltime gauge
zookeeper_requestthrottlestalltime 100.0
# HELP zookeeper_requestthrottlelimit RequestThrottleLimit (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>RequestThrottleLimit)
# TYPE zookeeper_requestthrottlelimit gauge
zookeeper_requestthrottlelimit 0.0
# HELP zookeeper_version Version (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>Version)
# TYPE zookeeper_version untyped
zookeeper_version{version="3.6.3--6401e4ad2087061bc6b9f80dec2d69f2e3c8660a, built on 04/08/2021 16:35 GMT",server_name="StandaloneServer_port2181",} 1.0
# HELP zookeeper_minsessiontimeout MinSessionTimeout (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MinSessionTimeout)
# TYPE zookeeper_minsessiontimeout gauge
zookeeper_minsessiontimeout 4000.0
# HELP zookeeper_numaliveconnections NumAliveConnections (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>NumAliveConnections)
# TYPE zookeeper_numaliveconnections gauge
zookeeper_numaliveconnections 1.0
# HELP zookeeper_requeststalelatencycheck RequestStaleLatencyCheck (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>RequestStaleLatencyCheck)
# TYPE zookeeper_requeststalelatencycheck gauge
zookeeper_requeststalelatencycheck 0.0
# HELP zookeeper_starttime StartTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>StartTime)
# TYPE zookeeper_starttime untyped
zookeeper_starttime{starttime="Tue Mar 01 20:52:48 GMT 2022",server_name="StandaloneServer_port2181",} 1.0
# HELP zookeeper_connections_outstandingrequests OutstandingRequests (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>OutstandingRequests)
# TYPE zookeeper_connections_outstandingrequests untyped
zookeeper_connections_outstandingrequests{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 0.0
# HELP zookeeper_connections_avglatency AvgLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>AvgLatency)
# TYPE zookeeper_connections_avglatency untyped
zookeeper_connections_avglatency{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 0.0
# HELP zookeeper_requeststaleconnectioncheck RequestStaleConnectionCheck (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>RequestStaleConnectionCheck)
# TYPE zookeeper_requeststaleconnectioncheck gauge
zookeeper_requeststaleconnectioncheck 1.0
# HELP zookeeper_nonmtlslocalconncount NonMTLSLocalConnCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>NonMTLSLocalConnCount)
# TYPE zookeeper_nonmtlslocalconncount gauge
zookeeper_nonmtlslocalconncount 0.0
# HELP zookeeper_inmemorydatatree_watchcount WatchCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=InMemoryDataTree><>WatchCount)
# TYPE zookeeper_inmemorydatatree_watchcount gauge
zookeeper_inmemorydatatree_watchcount{server_id="1",server_name="StandaloneServer_port2181",} 16.0
# HELP zookeeper_maxcnxns MaxCnxns (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxCnxns)
# TYPE zookeeper_maxcnxns gauge
zookeeper_maxcnxns 0.0
# HELP zookeeper_connectiondropincrease ConnectionDropIncrease (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionDropIncrease)
# TYPE zookeeper_connectiondropincrease gauge
zookeeper_connectiondropincrease 0.02
# HELP zookeeper_connections_lastlatency LastLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>LastLatency)
# TYPE zookeeper_connections_lastlatency untyped
zookeeper_connections_lastlatency{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 0.0
# HELP zookeeper_clientport ClientPort (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ClientPort)
# TYPE zookeeper_clientport untyped
zookeeper_clientport{clientport="2181",server_name="StandaloneServer_port2181",} 1.0
# HELP zookeeper_requestthrottledropstale RequestThrottleDropStale (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>RequestThrottleDropStale)
# TYPE zookeeper_requestthrottledropstale gauge
zookeeper_requestthrottledropstale 1.0
# HELP zookeeper_outstandingrequests OutstandingRequests (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>OutstandingRequests)
# TYPE zookeeper_outstandingrequests gauge
zookeeper_outstandingrequests 0.0
# HELP zookeeper_inmemorydatatree_nodecount NodeCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=InMemoryDataTree><>NodeCount)
# TYPE zookeeper_inmemorydatatree_nodecount gauge
zookeeper_inmemorydatatree_nodecount{server_id="1",server_name="StandaloneServer_port2181",} 211.0
# HELP zookeeper_lastclientresponsesize LastClientResponseSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>LastClientResponseSize)
# TYPE zookeeper_lastclientresponsesize gauge
zookeeper_lastclientresponsesize 16.0
# HELP zookeeper_connectionmaxtokens ConnectionMaxTokens (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionMaxTokens)
# TYPE zookeeper_connectionmaxtokens gauge
zookeeper_connectionmaxtokens 0.0
# HELP zookeeper_fsyncthresholdexceedcount FsyncThresholdExceedCount (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>FsyncThresholdExceedCount)
# TYPE zookeeper_fsyncthresholdexceedcount gauge
zookeeper_fsyncthresholdexceedcount 0.0
# HELP zookeeper_connections_packetssent PacketsSent (org.apache.ZooKeeperService<name0=StandaloneServer_port2181, name1=Connections, name2=172.20.0.9, name3=0x10000453ee7000a><>PacketsSent)
# TYPE zookeeper_connections_packetssent untyped
zookeeper_connections_packetssent{client_address="172.20.0.9",connection_id="0x10000453ee7000a",server_name="StandaloneServer_port2181",} 2193.0
# HELP zookeeper_connectiontokenfilltime ConnectionTokenFillTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionTokenFillTime)
# TYPE zookeeper_connectiontokenfilltime gauge
zookeeper_connectiontokenfilltime 1.0
# HELP zookeeper_txnlogelapsedsynctime TxnLogElapsedSyncTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>TxnLogElapsedSyncTime)
# TYPE zookeeper_txnlogelapsedsynctime gauge
zookeeper_txnlogelapsedsynctime 22.0
# HELP zookeeper_maxbatchsize MaxBatchSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxBatchSize)
# TYPE zookeeper_maxbatchsize gauge
zookeeper_maxbatchsize 1000.0
# HELP zookeeper_commitprocmaxcommitbatchsize CommitProcMaxCommitBatchSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>CommitProcMaxCommitBatchSize)
# TYPE zookeeper_commitprocmaxcommitbatchsize gauge
zookeeper_commitprocmaxcommitbatchsize 0.0
# HELP zookeeper_flushdelay FlushDelay (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>FlushDelay)
# TYPE zookeeper_flushdelay gauge
zookeeper_flushdelay 0.0
# HELP zookeeper_avgrequestlatency AvgRequestLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>AvgRequestLatency)
# TYPE zookeeper_avgrequestlatency gauge
zookeeper_avgrequestlatency 0.4071
# HELP zookeeper_datadirsize DataDirSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>DataDirSize)
# TYPE zookeeper_datadirsize gauge
zookeeper_datadirsize 8.7241544E8
# HELP zookeeper_connectionfreezetime ConnectionFreezeTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionFreezeTime)
# TYPE zookeeper_connectionfreezetime gauge
zookeeper_connectionfreezetime -1.0
# HELP zookeeper_maxwritequeuepolltime MaxWriteQueuePollTime (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxWriteQueuePollTime)
# TYPE zookeeper_maxwritequeuepolltime gauge
zookeeper_maxwritequeuepolltime 0.0
# HELP zookeeper_minrequestlatency MinRequestLatency (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MinRequestLatency)
# TYPE zookeeper_minrequestlatency gauge
zookeeper_minrequestlatency 0.0
# HELP zookeeper_packetsreceived PacketsReceived (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>PacketsReceived)
# TYPE zookeeper_packetsreceived gauge
zookeeper_packetsreceived 17341.0
# HELP zookeeper_maxclientresponsesize MaxClientResponseSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxClientResponseSize)
# TYPE zookeeper_maxclientresponsesize gauge
zookeeper_maxclientresponsesize 636.0
# HELP zookeeper_logdirsize LogDirSize (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>LogDirSize)
# TYPE zookeeper_logdirsize gauge
zookeeper_logdirsize 429158.0
# HELP zookeeper_largerequestmaxbytes LargeRequestMaxBytes (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>LargeRequestMaxBytes)
# TYPE zookeeper_largerequestmaxbytes gauge
zookeeper_largerequestmaxbytes 1.048576E8
# HELP zookeeper_responsecachingenabled ResponseCachingEnabled (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ResponseCachingEnabled)
# TYPE zookeeper_responsecachingenabled gauge
zookeeper_responsecachingenabled 1.0
# HELP zookeeper_largerequestthreshold LargeRequestThreshold (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>LargeRequestThreshold)
# TYPE zookeeper_largerequestthreshold gauge
zookeeper_largerequestthreshold -1.0
# HELP zookeeper_maxclientcnxnsperhost MaxClientCnxnsPerHost (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>MaxClientCnxnsPerHost)
# TYPE zookeeper_maxclientcnxnsperhost gauge
zookeeper_maxclientcnxnsperhost 60.0
# HELP zookeeper_connectiondecreaseratio ConnectionDecreaseRatio (org.apache.ZooKeeperService<name0=StandaloneServer_port2181><>ConnectionDecreaseRatio)
# TYPE zookeeper_connectiondecreaseratio gauge
zookeeper_connectiondecreaseratio 0.0
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.003229324
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP jmx_scrape_cached_beans Number of beans with their matching rule cached
# TYPE jmx_scrape_cached_beans gauge
jmx_scrape_cached_beans 0.0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 174.52
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.646167967675E9
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 128.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 3.220774912E9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 4.79141888E8
# HELP jvm_info VM version info
# TYPE jvm_info gauge
jvm_info{runtime="OpenJDK Runtime Environment",vendor="Azul Systems, Inc.",version="11.0.13+8-LTS",} 1.0
# HELP jmx_config_reload_failure_created Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_created gauge
jmx_config_reload_failure_created 1.646167967908E9
# HELP jmx_config_reload_success_created Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_created gauge
jmx_config_reload_success_created 1.646167967907E9
# HELP jvm_memory_pool_allocated_bytes_created Total bytes allocated in a given JVM memory pool. Only updated after GC, not continuously.
# TYPE jvm_memory_pool_allocated_bytes_created gauge
jvm_memory_pool_allocated_bytes_created{pool="CodeHeap 'profiled nmethods'",} 1.646167968416E9
jvm_memory_pool_allocated_bytes_created{pool="G1 Old Gen",} 1.646167968418E9
jvm_memory_pool_allocated_bytes_created{pool="G1 Eden Space",} 1.646167968418E9
jvm_memory_pool_allocated_bytes_created{pool="CodeHeap 'non-profiled nmethods'",} 1.646167968418E9
jvm_memory_pool_allocated_bytes_created{pool="G1 Survivor Space",} 1.646167968418E9
jvm_memory_pool_allocated_bytes_created{pool="Compressed Class Space",} 1.646167968418E9
jvm_memory_pool_allocated_bytes_created{pool="Metaspace",} 1.646167968418E9
jvm_memory_pool_allocated_bytes_created{pool="CodeHeap 'non-nmethods'",} 1.646167968418E9`

**Comment by hifly81** [comment]
Hi @michelmondor-sc could you re-write the content of this issue? Formatting is really bad

**Comment by hifly81** [comment]
hey, this has been solved by
https://github.com/confluentinc/jmx-monitoring-stacks/pull/160
