### ISSUE TITLE
Connect - CPU total

### ISSUE THREAD

**Issue by antonyaugustus** [confluentinc/jmx-monitoring-stacks#74]
Should this be a multiple of 100 to better correlate the metrics to the actual cores available on the server?

[connect-overview.json](https://github.com/confluentinc/jmx-monitoring-stacks/blob/6.0.1-post/jmxexporter-prometheus-grafana/assets/prometheus/grafana/provisioning/dashboards/connect-overview.json)

rate(process_cpu_seconds_total{job="connect",env="$env",cluster=~"$cluster",instance=~"$instance"}[5m])*100

**Comment by pneff93** [comment]
@hifly81, I think we can close it. it is solved with this commit https://github.com/confluentinc/jmx-monitoring-stacks/pull/183
