### ISSUE TITLE
Unable to get kafka_connect_cluster_id from JMX exporter

### ISSUE THREAD

**Issue by carao2020** [confluentinc/jmx-monitoring-stacks#75]
After importing JMX exporter config file, I couldnt find kafka_connect_cluster_id metric under the metric key kafka_connect_app_info.

This is showing only below mentioned metrics.

kafka_connect_app_info{start_time_ms="1652081661119",client_id="connect-1",job="kafka-connect"} 1.0
kafka_connect_app_info{commit_id="c6d7e3013b411760",client_id="connect-1",job="kafka-connect"} 1.0
kafka_connect_app_info{version="7.0.0-ccs",client_id="connect-1",job="kafka-connect"} 1.0

**Comment by jeqo** [comment]
This variable is defined on the Prometheus target 
config: https://github.com/confluentinc/jmx-monitoring-stacks/blob/36d7d0c26af27fa8f2dc85f357d6a5f60f83f488/jmxexporter-prometheus-grafana/assets/prometheus/prometheus-config/prometheus.yml#L85

**Comment by hifly81** [comment]
Hi @carao2020 are you satisfied with last answer? can we close the issue?

**Comment by hifly81** [comment]
closed due to inactivity
