### ISSUE TITLE
zookeeper avg request latency is multiplied by ticktime

### ISSUE THREAD

**Issue by bb01100100** [confluentinc/jmx-monitoring-stacks#78]
In the grafana dashboard for Zookeeper, I see that the latency metrics are being [multiplied by zookeeper ticktime](https://github.com/confluentinc/jmx-monitoring-stacks/blob/98e16b4f26f052c61152909f4a452c85d223dd43/jmxexporter-prometheus-grafana/assets/grafana/provisioning/dashboards/zookeeper-cluster.json#L894). This has the effect of multiplying ZK request latency by 3000 (the default ticktime in my ZK version).

That change was introduced as part of the following PR: https://github.com/confluentinc/jmx-monitoring-stacks/pull/22

What is the rationale for doing this?

**Comment by jeqo** [comment]
Zookeeper latency is ([was?](https://issues.apache.org/jira/browse/ZOOKEEPER-2641)) measured in ticks, that's why this avg latency was 0 most of the time. 
If it has changes we can update it for later versions of zookeeper (or wait for KRaft :))

**Comment by hifly81** [comment]
fixed with:
https://github.com/confluentinc/jmx-monitoring-stacks/pull/172
