### ISSUE TITLE
Add cluster linking jmx metrics for kafka

### ISSUE THREAD

**Issue by 2190413** [confluentinc/jmx-monitoring-stacks#85]
We have a kafka cluster of 5 brokers. And have setup cluster linking with the DR environment. Want to setup grafana dashboard for cluster linking so that we can pull metrics for the same.

**Comment by jeqo** [comment]
Hi there! Haven't got bandwidth to work on this. Is this something you'd like to contribute to the project?

**Comment by hifly81** [comment]
fixed
