### ISSUE TITLE
Requested - Dashboard for Confluent Platform Rest-Proxy 

### ISSUE THREAD

**Issue by sharonhac** [confluentinc/jmx-monitoring-stacks#91]
Hi , we are exposing metrics using kafka-rest.yml that you supplied using a specified port on the Kafka-Rest process , and able to view the related metrics , however - we didn't find a Dashboard json file for Grafana , 
is it something that you can deliver ? 
Thanks

**Comment by hifly81** [comment]
Hi @sharonhac, thanks for your interest. I will put this request in Evaluating.

**Comment by hifly81** [comment]
https://docs.confluent.io/platform/current/kafka-rest/production-deployment/rest-proxy/monitoring.html

**Comment by hifly81** [comment]
Fixed with https://github.com/confluentinc/jmx-monitoring-stacks/pull/167
