### ISSUE TITLE
JMX broker performance improvement

### ISSUE THREAD

**Issue by gadelkareem** [confluentinc/jmx-monitoring-stacks#95]
I opened this issue on https://github.com/confluentinc/cp-ansible/issues/1242 but maybe we can get a list of whitelistObjectNames that is being used in the dashboards. Anyone got such a list?

**Comment by iAlex97** [comment]
I think it depends on your configured dashboards. As I only use the "cluster", "topics", "quotas" dashboards, I managed to reduce scrape timeout from over 30s to ~15s by blacklisting some more unused metrics.

```yaml
blacklistObjectNames:
  - "kafka.consumer:type=*,id=*"
  - "kafka.consumer:type=*,client-id=*"
  - "kafka.consumer:type=*,client-id=*,node-id=*"
  - "kafka.producer:type=*,id=*"
  - "kafka.producer:type=*,client-id=*"
  - "kafka.producer:type=*,client-id=*,node-id=*"
  - "kafka.*:type=kafka-metrics-count,*"
  # This will ignore the admin client metrics from Kafka Brokers and will blacklist certain metrics
  # that do not make sense for ingestion.
  # "kafka.admin.client:type=*, node-id=*, client-id=*"
  # "kafka.admin.client:type=*, client-id=*"
  # "kafka.admin.client:type=*, id=*"
  - "kafka.admin.client:*"
  - "kafka.server:type=*,cipher=*,protocol=*,listener=*,networkProcessor=*"
  - "kafka.server:type=*"
  # newly blacklisted metrics
  - "kafka.log:type=Log,name=NumLogSegments,partition=*,topic=*"
  - "kafka.server:type=FetcherLagMetrics,name=ConsumerLag,clientId=*,partition=*,topic=*"
  - "kafka.cluster:type=Partition,name=ReplicasCount,partition=*,topic=*"
  - "kafka.cluster:type=Partition,name=LastStableOffsetLag,partition=*,topic=*"
```

**Comment by hifly81** [comment]
Hi @gadelkareem are you satisfied with 

> I think it depends on your configured dashboards. As I only use the "cluster", "topics", "quotas" dashboards, I managed to reduce scrape duration from over 30s to ~15s by blacklisting some more unused metrics.
> 
> ```yaml
> blacklistObjectNames:
>   - "kafka.consumer:type=*,id=*"
>   - "kafka.consumer:type=*,client-id=*"
>   - "kafka.consumer:type=*,client-id=*,node-id=*"
>   - "kafka.producer:type=*,id=*"
>   - "kafka.producer:type=*,client-id=*"
>   - "kafka.producer:type=*,client-id=*,node-id=*"
>   - "kafka.*:type=kafka-metrics-count,*"
>   # This will ignore the admin client metrics from Kafka Brokers and will blacklist certain metrics
>   # that do not make sense for ingestion.
>   # "kafka.admin.client:type=*, node-id=*, client-id=*"
>   # "kafka.admin.client:type=*, client-id=*"
>   # "kafka.admin.client:type=*, id=*"
>   - "kafka.admin.client:*"
>   - "kafka.server:type=*,cipher=*,protocol=*,listener=*,networkProcessor=*"
>   - "kafka.server:type=*"
>   # newly blacklisted metrics
>   - "kafka.log:type=Log,name=NumLogSegments,partition=*,topic=*"
>   - "kafka.server:type=FetcherLagMetrics,name=ConsumerLag,clientId=*,partition=*,topic=*"
>   - "kafka.cluster:type=Partition,name=ReplicasCount,partition=*,topic=*"
>   - "kafka.cluster:type=Partition,name=LastStableOffsetLag,partition=*,topic=*"
> ```

Hi @gadelkareem are you satisfied with this suggestion? can we close the issue?

**Comment by gadelkareem** [comment]
Yes, thanks @hifly81
