### ISSUE TITLE
MONITORING_STACK/start.sh does not spawn everything is needed

### ISSUE THREAD

**Issue by kagedani** [confluentinc/jmx-monitoring-stacks#99]
Hi, 

I'm trying to setup the environment for some tests. 
I've followed along the readme the paragraph "[How to run the cp-demo](https://github.com/confluentinc/jmx-monitoring-stacks#how-to-run-with-cp-demo)" but when I submit the command: 
`${MONITORING_STACK}/start.sh`
the script is unable to spawn the cp demo cluster, I think. 
Here is the log messages:

> Using<CUSTOM_PATH>/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/docker-compose.override.yaml for docker-compose override
> Launch cp-demo in <CUSTOM_PATH>/cp-demo (version CONFLUENT_DOCKER_TAG=7.2.0) and monitoring stack in /mnt/c/Git/BNL/stream-monitoring/jmx-monitoring-stacks/jmxexporter-prometheus-grafana
> 
> ERROR: This script requires 'jq'. Please install 'jq' and run again.
> 
> Create user and certificates for kafkaLagExporter
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 8: keytool: command not found
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 19: keytool: command not found
> Can't open kafkaLagExporter.csr for reading, No such file or directory
> 140184797439296:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('kafkaLagExporter.csr','r')
> 140184797439296:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 52: keytool: command not found
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 56: keytool: command not found
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 60: keytool: command not found
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 71: keytool: command not found
> Can't open kafkaLagExporter.der for reading, No such file or directory
> 140005585380672:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('kafkaLagExporter.der','rb')
> 140005585380672:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
> unable to load certificate
> <CUSTOM_PATH>/cp-demo/scripts/security/certs-create-per-user.sh: line 73: keytool: command not found
> Can't open kafkaLagExporter.keystore.p12 for reading, No such file or directory
> 140442245539136:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('kafkaLagExporter.keystore.p12','rb')
> 140442245539136:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
> Create role binding for kafkaLagExporter
> jmxexporter-prometheus-grafana/start.sh: line 38: jq: command not found
> Launch <CUSTOM_PATH>/jmx-monitoring-stacks/jmxexporter-prometheus-grafana
> WARNING: The REPOSITORY variable is not set. Defaulting to a blank string.
> WARNING: The SSL_CIPHER_SUITES variable is not set. Defaulting to a blank string.
> WARNING: The CONNECTOR_VERSION variable is not set. Defaulting to a blank string.
> WARNING: The CONTROL_CENTER_KSQL_WIKIPEDIA_URL variable is not set. Defaulting to a blank string.
> WARNING: The CONTROL_CENTER_KSQL_WIKIPEDIA_ADVERTISED_URL variable is not set. Defaulting to a blank string.
> 

The script indeed proceeds and setup the grafana-prometheus & co part. 
In fact I have the following container correctly set up:
![immagine](https://user-images.githubusercontent.com/118300808/223142901-1e01e32f-6045-41cd-9a3e-8fb30695d454.png)

But unfortunately, when I login to Grafana, all Kafka dashboards are empty. 

Could you please help? Am I doing something wrong?

OS: Windows 11 (with ubuntu 20.04 WSL)

**Comment by phy2000** [comment]
Maybe this error is causing the issue:
`ERROR: This script requires 'jq'. Please install 'jq' and run again.`

**Comment by hifly81** [comment]
Hi @kagedani are you satisfied with last reply? could we close the issue?

**Comment by kagedani** [comment]
> Maybe this error is causing the issue: `ERROR: This script requires 'jq'. Please install 'jq' and run again.`

Where do I need to install jq? Directly on my pc?
I think that error management here is not performed correctly: having the containers up&running but without info displayed it's not a good way to start

**Comment by hifly81** [comment]
> > Maybe this error is causing the issue: `ERROR: This script requires 'jq'. Please install 'jq' and run again.`
> 
> Where do I need to install jq? Directly on my pc? I think that error management here is not performed correctly: having the containers up&running but without info displayed it's not a good way to start

@kagedani jq is required on your machine. I will keep the issue opened and list in README the required software to run the demo
